server {
    listen 80;
    server_name arenic.online www.arenic.online;

    # Certbot challenge location
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

#server {
#    listen 443 ssl;
#    server_name arenic.online www.arenic.online;
#
#    # SSL Certificate Paths (managed by Certbot volume)
#    ssl_certificate /etc/letsencrypt/live/arenic.online/fullchain.pem;
#    ssl_certificate_key /etc/letsencrypt/live/arenic.online/privkey.pem;
#
#    # Optimization for $4 VPS
#    ssl_session_cache shared:SSL:10m;
#    ssl_session_timeout 10m;
#
#    # Angular static files
#    location / {
#        root /usr/share/nginx/html; #using the folder where we copied the compiled angular app using the frontend/Dockerfile
#        index index.html;
#        try_files $uri $uri/ /index.html;
#    }
#
#    # Proxy API requests to Spring Boot
#    location /api/ {
#        proxy_pass http://spring_backend:8080/api/; #using the docker service name configured in the docker-compose
#        proxy_http_version 1.1;
#        proxy_set_header Upgrade $http_upgrade;
#        proxy_set_header Connection 'upgrade';
#        proxy_set_header Host $host;
#        proxy_cache_bypass $http_upgrade;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto $scheme;
#    }
#}
