spring:
  config:
    #we make it optional because is just for local dev, since inside the prd docker the env var are loaded with env_file:
    import: "optional:file:../.env[.properties]"
  application:
    name: backend

  # Database Connection
  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # JPA / Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  # Flyway settings
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    locations:
      - classpath:db/migration

  # Auth tokens and spring security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            #é a que pon springsecurity por defecto pero deixoa a modo de documentación
            redirect-uri: "{baseUri}/login/oauth2/code/{registrationId}"
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
      expiration-time: ${JWT_EXPIRATION_MS}

# WebServer config
server:
  port: 8080
  servlet:
    context-path: /api
